name = "liminall-node-engine"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "liminall-node"
database_id = "35b44425-a32a-4a74-bcae-267abaa5f3ea"

[[r2_buckets]]
binding = "NODE_IMAGES"
bucket_name = "liminall-node-images"