name = "muistoissa-engine"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "muistoissa-db"
database_id = "0e0eb9e9-9fc7-41cd-9fc3-08a20ff054be"

[[r2_buckets]]
binding = "NODE_IMAGES"
bucket_name = "muistoissa-images"
